obstacles:
        -    shape: Star
             star:
                    -    type: Rectangular
                         center:
                               - 6.77
                               - 1.1
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.99


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 1.99
                               - 1.05
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0

        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 1.99
                               - 1.65
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 3.13
                               - 1.05
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0

        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 3.13
                               - 1.65
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.56
                               - 1.35
                         width: 0.5
                         height: 1.2
                         theta: 0.0
                         s: 0.99


        -    shape: StarTree
             stars:
                     -   type: Rectangular
                         center:
                               - 4.37
                               - 2.30
                         width: 0.8
                         height: 0.2
                         theta: 0.5
                         s: 0.99

                     -   type: Rectangular
                         center:
                               - 4.4
                               - 2.88
                         width: 0.2
                         height: 1.2
                         theta: 0.5
                         s: 0.99


workspace:
        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.9999

                    -    type: Rectangular
                         center:
                               - 6.43
                               - 2.2
                         width: 1.5
                         height: 0.2
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.7
                               - 2.45
                         width: 0.2
                         height: 0.6
                         theta: 0.2
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.7
                               - 3.85
                         width: 0.2
                         height: 0.6
                         theta: -0.2
                         s: 0.99


        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.45
                               - 0.505
                         width: 0.2
                         height: 1.4
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.6
                               - 1.1
                         width: 0.5
                         height: 0.2
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 3.95
                               - 0.505
                         width: 0.2
                         height: 1.4
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 4.15
                               - 1.1
                         width: 0.6
                         height: 0.2
                         theta: 0.0
                         s: 0.99


        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 1.6
                               - 3.5
                         width: 0.2
                         height: 1.4
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 2.05
                               - 2.9
                         width: 1.7
                         height: 0.2
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 2.8
                               - 3.1
                         width: 0.2
                         height: 0.6
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 0.05
                               - 2.9
                         width: 0.5
                         height: 0.2
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 0.4
                               - 1.5
                         width: 1.2
                         height: 0.2
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 0.9
                               - 1.7
                         width: 0.2
                         height: 0.6
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 1.0
                               - 0.3
                         width: 0.2
                         height: 1.0
                         theta: 0.0
                         s: 0.99

#nf_lambda=1e2, nf_mu = [1e25, 1e16, 1e10]